import { Version } from "google-protobuf/google/protobuf/compiler/plugin_pb";
import { version as packageVersion } from "../../package.json";

export function generateHeaderComment(compilerVersion: Version | undefined) {
  let comment = "";

  comment += `// Code generated by protoc-gen-as. DO NOT EDIT.\n`;
  comment += `// Versions:\n`;
  comment += `//   protoc-gen-as v${packageVersion}\n`;

  if (compilerVersion) {
    comment += `//   protoc        v${versionString(compilerVersion)}\n`;
  }

  return comment;
}

/**
 * @Returns a human-readable version string based on the `Version` type
 * provided by the Protobuf compiler.
 */
function versionString(version: Version): string {
  const [ major, minor, patch, suffix ] = version.toArray();

  if (suffix) {
    return `${major}.${minor}.${patch}-${suffix}`;
  } else {
    return `${major}.${minor}.${patch}`;
  }
}
