import { Version } from "google-protobuf/google/protobuf/compiler/plugin_pb";

export function generateHeaderComment(compilerVersion: Version | undefined) {
  let comment = "";
  const { version: packageVersion } = require("../../package.json"); // relative to /lib/generate directory

  comment += `// Code generated by protoc-gen-as. DO NOT EDIT.\n`;
  if (packageVersion || compilerVersion) {
    comment += `// Versions:\n`;
    if (packageVersion) {
      comment += `//   protoc-gen-as v${packageVersion}\n`;
    }
    if (compilerVersion) {
      comment += `//   protoc        v${versionString(compilerVersion)}\n`;
    }
  }

  return comment;
}

/**
 * @returns a human-readable version string based on the `Version` type
 * provided by the Protobuf compiler.
 */
function versionString(version: Version): string {
  const [major, minor, patch, suffix] = version.toArray();

  if (suffix) {
    return `${major}.${minor}.${patch}-${suffix}`;
  } else {
    return `${major}.${minor}.${patch}`;
  }
}
